//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class BasePapersEntities : DbContext
    {
        public BasePapersEntities()
            : base("name=BasePapersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Auths_papers> Auths_papers { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Language> Languages { get; set; }
        public DbSet<Organisation> Organisations { get; set; }
        public DbSet<Paper> Papers { get; set; }
        public DbSet<Reviewers_papers> Reviewers_papers { get; set; }
        public DbSet<Scientist> Scientists { get; set; }
        public DbSet<Subject> Subjects { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("diagramname", diagramname) :
                new System.Data.Entity.Core.Objects.ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("owner_id", owner_id) :
                new System.Data.Entity.Core.Objects.ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("version", version) :
                new System.Data.Entity.Core.Objects.ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("definition", definition) :
                new System.Data.Entity.Core.Objects.ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("diagramname", diagramname) :
                new System.Data.Entity.Core.Objects.ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("owner_id", owner_id) :
                new System.Data.Entity.Core.Objects.ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("version", version) :
                new System.Data.Entity.Core.Objects.ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("definition", definition) :
                new System.Data.Entity.Core.Objects.ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("diagramname", diagramname) :
                new System.Data.Entity.Core.Objects.ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("owner_id", owner_id) :
                new System.Data.Entity.Core.Objects.ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }

        public virtual System.Data.Entity.Core.Objects.ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("diagramname", diagramname) :
                new System.Data.Entity.Core.Objects.ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("owner_id", owner_id) :
                new System.Data.Entity.Core.Objects.ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual System.Data.Entity.Core.Objects.ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("diagramname", diagramname) :
                new System.Data.Entity.Core.Objects.ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("owner_id", owner_id) :
                new System.Data.Entity.Core.Objects.ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("diagramname", diagramname) :
                new System.Data.Entity.Core.Objects.ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("owner_id", owner_id) :
                new System.Data.Entity.Core.Objects.ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("new_diagramname", new_diagramname) :
                new System.Data.Entity.Core.Objects.ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
