//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organisation
    {
        public Organisation()
        {
            this.Scientists = new HashSet<Scientist>();
        }
    
        public int org_id { get; set; }
        public string org_name { get; set; }
        public int org_country { get; set; }
        public string org_website { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<Scientist> Scientists { get; set; }
    }
}
