//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paper
    {
        public Paper()
        {
            this.Auths_papers = new HashSet<Auths_papers>();
            this.Reviewers_papers = new HashSet<Reviewers_papers>();
        }
    
        public int p_id { get; set; }
        public string p_title { get; set; }
        public string p_abstract { get; set; }
        public System.DateTime p_date { get; set; }
        public int language_id { get; set; }
        public int subj_id { get; set; }
    
        public virtual ICollection<Auths_papers> Auths_papers { get; set; }
        public virtual Language Language { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual ICollection<Reviewers_papers> Reviewers_papers { get; set; }
    }
}
