//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviewers_papers
    {
        public int paper_reviewer_id { get; set; }
        public int p_id { get; set; }
        public int s_id { get; set; }
        public string reviewer_comment { get; set; }
    
        public virtual Paper Paper { get; set; }
        public virtual Scientist Scientist { get; set; }
    }
}
